### ISSUE TITLE
How do you validate NRICs?

### ISSUE THREAD

**Issue by ninest** [bryanseah234/nric2003#1]
I found your repository under the Singapore topic on GitHub, and it looked pretty interesting.

I was wondering, what exactly are you doing to validate the NRIC in [02_validate nric2003.py](https://github.com/bryanseah234/nric2003/blob/master/02_validate%20nric2003.py)? Is the algorithm explained anywhere?

**Comment by bryanseah234** [comment]
Hi Ninest! Thank you for taking interest in this.
I am validating the NRICs according to their last alphabet . I believe it is called a checksum. This method of validation has been reversed engineered and a quick google search will yield back results on how to perform validation. I will link it here nonetheless: https://en.wikipedia.org/wiki/National_Registration_Identity_Card#Structure_of_the_NRIC_number/FIN

(that said, my code in 02_validate nric2003.py may not be totally flawless, but it did the job)
